export interface Node {
  name: string;
  title: string;
}

export interface NodeGroup {
  title: string;
  nodes: Node[];
}

/**
 * https://www.v2ex.com/?tab=nodes
 */
export const NODE_GROUP_LIST: NodeGroup[] = [
  {
    title: '分享与探索',
    nodes: [
      { name: 'qna', title: '问与答' },
      { name: 'share', title: '分享发现' },
      { name: 'create', title: '分享创造' },
      { name: 'ideas', title: '奇思妙想' },
      { name: 'in', title: '分享邀请码' },
      { name: 'autistic', title: '自言自语' },
      { name: 'design', title: '设计' },
      { name: 'blog', title: 'Blog' },
    ],
  },
  {
    title: 'V2EX',
    nodes: [
      { name: 'v2ex', title: 'V2EX' },
      { name: 'feedback', title: '反馈' },
      { name: 'babel', title: 'Project Babel' },
      { name: 'guide', title: '使用指南' },
    ],
  },
  {
    title: 'Apple',
    nodes: [
      { name: 'macos', title: 'macOS' },
      { name: 'apple', title: 'Apple' },
      { name: 'iphone', title: 'iPhone' },
      { name: 'mbp', title: 'MacBook Pro' },
      { name: 'ios', title: 'iOS' },
      { name: 'ipad', title: 'iPad' },
      { name: 'macbook', title: 'MacBook' },
      { name: 'watch', title: ' WATCH' },
      { name: 'accessory', title: '配件' },
      { name: 'mba', title: 'MacBook Air' },
      { name: 'imac', title: 'iMac' },
      { name: 'macmini', title: 'Mac mini' },
      { name: 'xcode', title: 'Xcode' },
      { name: 'macpro', title: 'Mac Pro' },
      { name: 'wwdc', title: 'WWDC' },
      { name: 'ipod', title: 'iPod' },
      { name: 'airpods', title: 'AirPods' },
      { name: 'mobileme', title: 'MobileMe' },
      { name: 'iwork', title: 'iWork' },
      { name: 'ilife', title: 'iLife' },
      { name: 'garageband', title: 'GarageBand' },
      { name: 'homekit', title: 'HomeKit' },
    ],
  },
  {
    title: '前端开发',
    nodes: [
      { name: 'wechat', title: '微信' },
      { name: 'chrome', title: 'Chrome' },
      { name: 'vue', title: 'Vue.js' },
      { name: 'css', title: 'CSS' },
      { name: 'browsers', title: '浏览器' },
      { name: 'react', title: 'React' },
      { name: 'firefox', title: 'Firefox' },
      { name: 'flutter', title: 'Flutter' },
      { name: 'angular', title: 'Angular' },
      { name: 'edge', title: 'Edge' },
      { name: 'electron', title: 'Electron' },
      { name: 'webdev', title: 'Web Dev' },
      { name: 'ionic', title: 'Ionic' },
      { name: 'nextjs', title: 'Next.js' },
      { name: 'nuxtjs', title: 'Nuxt.js' },
      { name: 'vite', title: 'Vite' },
    ],
  },
  {
    title: '编程语言',
    nodes: [
      { name: 'python', title: 'Python' },
      { name: 'java', title: 'Java' },
      { name: 'php', title: 'PHP' },
      { name: 'js', title: 'JavaScript' },
      { name: 'nodejs', title: 'Node.js' },
      { name: 'go', title: 'Go 编程语言' },
      { name: 'html', title: 'HTML' },
      { name: 'swift', title: 'Swift' },
      { name: 'dotnet', title: '.NET' },
      { name: 'ror', title: 'Ruby on Rails' },
      { name: 'rust', title: 'Rust' },
      { name: 'csharp', title: 'C#' },
      { name: 'ruby', title: 'Ruby' },
      { name: 'typescript', title: 'TypeScript' },
      { name: 'kotlin', title: 'Kotlin' },
      { name: 'lua', title: 'Lua' },
    ],
  },
  {
    title: '后端架构',
    nodes: [
      { name: 'cloud', title: '云计算' },
      { name: 'server', title: '服务器' },
      { name: 'dns', title: 'DNS' },
      { name: 'mysql', title: 'MySQL' },
      { name: 'nginx', title: 'NGINX' },
      { name: 'docker', title: 'Docker' },
      { name: 'db', title: '数据库' },
      { name: 'django', title: 'Django' },
      { name: 'mongodb', title: 'MongoDB' },
      { name: 'redis', title: 'Redis' },
      { name: 'devops', title: 'DevOps' },
      { name: 'k8s', title: 'Kubernetes' },
      { name: 'tornado', title: 'Tornado' },
      { name: 'elasticsearch', title: 'Elasticsearch' },
      { name: 'api', title: 'API' },
      { name: 'leancloud', title: 'LeanCloud' },
      { name: 'cloudflare', title: 'Cloudflare' },
      { name: 'timescale', title: 'Timescale' },
    ],
  },
  {
    title: '机器学习',
    nodes: [
      { name: 'ml', title: '机器学习' },
      { name: 'math', title: '数学' },
      { name: 'tensorflow', title: 'TensorFlow' },
      { name: 'nlp', title: '自然语言处理' },
      { name: 'cuda', title: 'CUDA' },
      { name: 'torch', title: 'Torch' },
      { name: 'coreml', title: 'Core ML' },
      { name: 'keras', title: 'Keras' },
    ],
  },
  {
    title: 'iOS',
    nodes: [
      { name: 'idev', title: 'iDev' },
      { name: 'icode', title: 'iCode' },
      { name: 'imarketing', title: 'iMarketing' },
      { name: 'iad', title: 'iAd' },
      { name: 'itransfer', title: 'iTransfer' },
    ],
  },
  {
    title: 'Geek',
    nodes: [
      { name: 'programmer', title: '程序员' },
      { name: 'bb', title: '宽带症候群' },
      { name: 'android', title: 'Android' },
      { name: 'linux', title: 'Linux' },
      { name: 'outsourcing', title: '外包' },
      { name: 'hardware', title: '硬件' },
      { name: 'bitcoin', title: 'Bitcoin' },
      { name: 'webmaster', title: '站长' },
      { name: 'car', title: '汽车' },
      { name: 'router', title: '路由器' },
      { name: 'programming', title: '编程' },
      { name: 'linode', title: 'Linode' },
      { name: 'designer', title: '设计师' },
      { name: 'markdown', title: 'Markdown' },
      { name: 'vscode', title: 'Visual Studio Code' },
      { name: 'kindle', title: 'Kindle' },
      { name: 'gamedev', title: '游戏开发' },
      { name: 'minecraft', title: 'Minecraft' },
      { name: 'typography', title: '字体排印' },
      { name: 'atom', title: 'Atom' },
      { name: 'business', title: '商业模式' },
      { name: 'sony', title: 'SONY' },
      { name: 'leetcode', title: 'LeetCode' },
      { name: 'photoshop', title: 'Photoshop' },
      { name: 'serverless', title: 'Serverless' },
      { name: 'amazon', title: 'Amazon' },
      { name: 'lego', title: 'LEGO' },
      { name: 'gitlab', title: 'GitLab' },
      { name: 'ev', title: '电动汽车' },
      { name: 'rss', title: 'RSS' },
      { name: 'dji', title: 'DJI' },
      { name: 'copilot', title: 'GitHub Copilot' },
      { name: 'miracleplus', title: '奇绩创坛' },
    ],
  },
  {
    title: '游戏',
    nodes: [
      { name: 'games', title: '游戏' },
      { name: 'steam', title: 'Steam' },
      { name: 'switch', title: 'Nintendo Switch' },
      { name: 'lol', title: '英雄联盟' },
      { name: 'ps4', title: 'PlayStation 4' },
      { name: 'igame', title: 'iGame' },
      { name: 'sc2', title: 'StarCraft 2' },
      { name: 'bf3', title: 'Battlefield 3' },
      { name: 'wow', title: 'World of Warcraft' },
      { name: '5v5', title: '王者荣耀' },
      { name: 'retro', title: '怀旧游戏' },
      { name: 'eve', title: 'EVE' },
      { name: 'pokemon', title: '精灵宝可梦' },
      { name: 'ps5', title: 'PlayStation 5' },
      { name: '3ds', title: '3DS' },
      { name: 'gt', title: 'Gran Turismo' },
      { name: 'bf4', title: 'Battlefield 4' },
      { name: 'wiiu', title: 'Wii U' },
      { name: 'bfv', title: 'Battlefield V' },
      { name: 'gamedb', title: 'GameDB' },
    ],
  },
  {
    title: '生活',
    nodes: [
      { name: 'all4all', title: '二手交易' },
      { name: 'jobs', title: '酷工作' },
      { name: 'career', title: '职场话题' },
      { name: 'cv', title: '求职' },
      { name: 'afterdark', title: '天黑以后' },
      { name: 'free', title: '免费赠送' },
      { name: 'music', title: '音乐' },
      { name: 'movie', title: '电影' },
      { name: 'exchange', title: '物物交换' },
      { name: 'invest', title: '投资' },
      { name: 'tuan', title: '团购' },
      { name: 'tv', title: '剧集' },
      { name: 'travel', title: '旅行' },
      { name: 'creditcard', title: '信用卡' },
      { name: 'taste', title: '美酒与美食' },
      { name: 'reading', title: '阅读' },
      { name: 'photograph', title: '摄影' },
      { name: 'pet', title: '宠物' },
      { name: 'baby', title: 'Baby' },
      { name: 'soccer', title: '绿茵场' },
      { name: 'coffee', title: '咖啡' },
      { name: 'diary', title: '日记' },
      { name: 'love', title: '非诚勿扰' },
      { name: 'bike', title: '骑行' },
      { name: 'plant', title: '植物' },
      { name: 'mushroom', title: '蘑菇' },
      { name: 'mileage', title: '行程控' },
    ],
  },
  {
    title: 'Internet',
    nodes: [
      { name: 'google', title: 'Google' },
      { name: 'youtube', title: 'YouTube' },
      { name: 'notion', title: 'Notion' },
      { name: 'reddit', title: 'Reddit' },
    ],
  },
  {
    title: '城市',
    nodes: [
      { name: 'beijing', title: '北京' },
      { name: 'shanghai', title: '上海' },
      { name: 'shenzhen', title: '深圳' },
      { name: 'hangzhou', title: '杭州' },
      { name: 'chengdu', title: '成都' },
      { name: 'guangzhou', title: '广州' },
      { name: 'wuhan', title: '武汉' },
      { name: 'nanjing', title: '南京' },
      { name: 'xian', title: '西安' },
      { name: 'kunming', title: '昆明' },
      { name: 'chongqing', title: '重庆' },
      { name: 'suzhou', title: '苏州' },
      { name: 'xiamen', title: '厦门' },
      { name: 'tianjin', title: '天津' },
      { name: 'qingdao', title: '青岛' },
      { name: 'sanfrancisco', title: 'San Francisco' },
      { name: 'nyc', title: 'New York' },
      { name: 'la', title: 'Los Angeles' },
      { name: 'tokyo', title: '东京' },
      { name: 'guiyang', title: '贵阳' },
      { name: 'singapore', title: 'Singapore' },
      { name: 'boston', title: 'Boston' },
    ],
  },
  {
    title: '品牌',
    nodes: [
      { name: 'uniqlo', title: 'UNIQLO' },
      { name: 'ikea', title: '宜家' },
      { name: 'lamy', title: 'Lamy' },
      { name: 'muji', title: '无印良品' },
      { name: 'nike', title: 'Nike' },
      { name: 'adidas', title: 'Adidas' },
      { name: 'gap', title: 'Gap' },
      { name: 'moleskine', title: 'Moleskine' },
      { name: 'gstar', title: 'G-Star' },
    ],
  },
];
